from Embellishment import Embellishment

g_g = Embellishment(["g"], 0)
g_G = Embellishment(["G"], 0)
g_a = Embellishment(["a"], 0)
g_d = Embellishment(["d"], 0)
g_e = Embellishment(["e"], 0)
g_gef = Embellishment(["G", "e", "f"], 0)    
g_gbd = Embellishment(["G", "b", "d"], 0)
g_gcd = Embellishment(["G", "c", "d"], 0)
g_dThrow = Embellishment(["g", "d", "c"], 0)
g_gbirl = Embellishment(["G", "a", "g", "a", "g"], 0)
g_birl = Embellishment(["g", "a", "g"], 0)
g_grip = Embellishment(["g", "d", "g"], 0)
g_gbg = Embellishment(["G", "b", "g"], 0)
g_ag = Embellishment(["G", "A"], 0)
g_ef = Embellishment(["e", "f"], 0)
